ALTER TABLE my_ways      ADD PRIMARY KEY (id);
ALTER TABLE my_areas     ADD PRIMARY KEY (id);
ALTER TABLE my_roads     ADD PRIMARY KEY (id);
ALTER TABLE my_relations ADD PRIMARY KEY (id);
ALTER TABLE my_nodes ADD PRIMARY KEY (id);
create index my_ways_geog_idx on my_ways using gist (geog);
create index my_nodes_geog_idx on my_nodes using gist (geog);
create index my_areas_geog_idx on my_areas using gist (geog);
create index my_relations_geog_idx on my_relations using gist (geog);
create index my_roads_geog_idx on my_roads using gist (geog);
