#pragma once

// Loads the natural-boundary region polygons (data/regions/<name>.wkt,
// generated by tools/prepare_regions.py) into Boost.Geometry types for
// in-process point-in-polygon testing. Boost.Geometry is header-only
// (same precedent as boost::json in AirspaceLoader.cpp) so this needs no
// new link libraries.
//
// See include/Regions.h for the canonical region name list and why the
// WKT files are the source of truth shared with regional_db_export.cpp's
// region_boundaries Postgres table.

#include <boost/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>

#include <string>
#include <unordered_map>
#include <vector>

namespace RegionPolygons {

using Point = boost::geometry::model::d2::point_xy<double>;
using Polygon = boost::geometry::model::polygon<Point>;
using MultiPolygon = boost::geometry::model::multi_polygon<Polygon>;

// Parses <dir>/<name>.wkt for every entry in allExportRegions() (Regions.h,
// primary + border regions), or only the given subset of names if `only` is
// non-empty (parsing an 800KB+
// multi-island WKT file is not free — skip the ones a caller filtered out
// via e.g. regional_export's --regions flag). Coordinates are WGS84 degrees
// (lon, lat) as stored in the WKT files — callers needing a different
// unit/projection (e.g. regional_export.cpp's Mercator meters, to match
// nodes.dat) must project the returned polygons themselves. Throws
// std::runtime_error if a region's WKT file is missing or fails to parse.
std::unordered_map<std::string, MultiPolygon> load(const std::string& dir,
                                                     const std::vector<std::string>& only = {});

// Parses one region's WKT text directly (not from a file) -- same format as
// a data/regions/<name>.wkt file's contents. Used by RegionalDeltaApplier's
// DB-driven region loading (NavDB::loadInstalledRegions() returns each
// installed region's WKT as plain text, not a file path). `context` is
// prepended to the error message on parse failure (e.g. the region name),
// since there's no file path to report here. Throws std::runtime_error on
// failure, same as load().
MultiPolygon parse(const std::string& wkt, const std::string& context = "");

} // namespace RegionPolygons
